#%RAML 1.0
title: Prueba Innovación API
baseUri: http://localhost:3000
version: v1
mediaType: application/json

types:
  User:
    type: object
    properties:
      _id: string
      name: string
      email: string
      password: string
      token: string

/login:
    post:
      description: Inicio de sesión con email y pasword para obtener token de acceso
      body:
        application/json:
          properties:
            email:
              type: string
              required: true
            password:
              type: string
              required: true
      responses:
        200:
          body:
            application/json:
              properties:
                token:
                  type: string
        401:
          body:
            application/json:
              properties:
                message:
                  type: string
        404:
          body:
            application/json:
              properties:
                message:
                  type: string
/new:
    post:
      description: Creación de nuevo usuario
      body:
        application/json:
          properties:
            name:
              type: string
              required: true
            email:
              type: string
              required: true
            password:
              type: string
              required: true
      responses:
        200:
          body:
            application/json:
              type: User
        400:
          body:
            application/json:
              properties:
                message:
                  type: string
        409:
          body:
            application/json:
              properties:
                message:
                  type: string
/me:
  get:
    description: Obtener detalle del usuario concurrente
    headers:
      prueba-token:
        description: Token obtenido desde el endpoint /login
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            type: User
      401:
        body:
          application/json:
            properties:
              message:
                type: string
      404:
        body:
          application/json:
            properties:
              message:
                type: string
  patch:
    description: Actualizar los datos del usuario concurrente
    headers:
      prueba-token:
        description: Token obtenido desde el endpoint /login
        type: string
        required: true
    body:
      application/json:
        properties:
          name:
            type: string
          email:
            type: string
          password:
            type: string
    responses:
      200:
        body:
          application/json:
            type: User
      401:
        body:
          application/json:
            properties:
              message:
                type: string
      404:
        body:
          application/json:
            properties:
              message:
                type: string
  delete:
    description: Borrar el usuario cocurrente
    headers:
      prueba-token:
        description: Token obtenido desde el endpoint /login
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            type: User
      401:
        body:
          application/json:
            properties:
              message:
                type: string
      404:
        body:
          application/json:
            properties:
              message:
                type: string